# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: lfx-v2-meeting-service
  namespace: {{ .Values.lfx.namespace }}
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: {{ .Values.traefik.gateway.name }}
    namespace: {{ .Values.traefik.gateway.namespace }}
  hostnames:
  - "lfx-api.{{ .Values.lfx.domain }}"
  rules:
  # ITX proxy endpoints and OpenAPI documentation
  - matches:
    - path:
        type: PathPrefix
        value: /itx/meetings
    - path:
        type: PathPrefix
        value: /itx/past_meetings
    - path:
        type: Exact
        value: /itx/meeting_count
    - path:
        type: PathPrefix
        value: /_meetings/
    {{- if .Values.heimdall.enabled }}
    filters:
    - type: ExtensionRef
      extensionRef:
        group: traefik.io
        kind: Middleware
        name: heimdall-forward-body
    {{- end }}
    backendRefs:
    - group: ''
      kind: Service
      name: lfx-v2-meeting-service
      port: {{ .Values.service.port }}
      weight: 1
