# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
---
{{- if .Values.nats.object_store_meeting_attachments.creation }}
apiVersion: jetstream.nats.io/v1beta2
kind: ObjectStore
metadata:
  name: {{ .Values.nats.object_store_meeting_attachments.name }}
  namespace: lfx
  {{- if .Values.nats.object_store_meeting_attachments.keep }}
  annotations:
    "helm.sh/resource-policy": keep
  {{- end }}
spec:
  bucket: {{ .Values.nats.object_store_meeting_attachments.name }}
  storage: {{ .Values.nats.object_store_meeting_attachments.storage }}
  maxBytes: {{ .Values.nats.object_store_meeting_attachments.maxBytes }}
{{- end }}
