# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
---
{{- if .Values.nats.kv_bucket_meetings.creation }}
apiVersion: jetstream.nats.io/v1beta2
kind: KeyValue
metadata:
  name: {{ .Values.nats.kv_bucket_meetings.name }}
  namespace: lfx
  {{- if .Values.nats.kv_bucket_meetings.keep }}
  annotations:
    "helm.sh/resource-policy": keep
  {{- end }}
spec:
  bucket: {{ .Values.nats.kv_bucket_meetings.name }}
  history: {{ .Values.nats.kv_bucket_meetings.history }}
  storage: {{ .Values.nats.kv_bucket_meetings.storage }}
  maxValueSize: {{ .Values.nats.kv_bucket_meetings.maxValueSize }}
  maxBytes: {{ .Values.nats.kv_bucket_meetings.maxBytes }}
  compression: {{ .Values.nats.kv_bucket_meetings.compression }}
{{- end }}
---
{{- if .Values.nats.kv_bucket_meeting_settings.creation }}
apiVersion: jetstream.nats.io/v1beta2
kind: KeyValue
metadata:
  name: {{ .Values.nats.kv_bucket_meeting_settings.name }}
  namespace: lfx
  {{- if .Values.nats.kv_bucket_meeting_settings.keep }}
  annotations:
    "helm.sh/resource-policy": keep
  {{- end }}
spec:
  bucket: {{ .Values.nats.kv_bucket_meeting_settings.name }}
  history: {{ .Values.nats.kv_bucket_meeting_settings.history }}
  storage: {{ .Values.nats.kv_bucket_meeting_settings.storage }}
  maxValueSize: {{ .Values.nats.kv_bucket_meeting_settings.maxValueSize }}
  maxBytes: {{ .Values.nats.kv_bucket_meeting_settings.maxBytes }}
  compression: {{ .Values.nats.kv_bucket_meeting_settings.compression }}
{{- end }}
---
{{- if .Values.nats.kv_bucket_meeting_registrants.creation }}
apiVersion: jetstream.nats.io/v1beta2
kind: KeyValue
metadata:
  name: {{ .Values.nats.kv_bucket_meeting_registrants.name }}
  namespace: lfx
  {{- if .Values.nats.kv_bucket_meeting_registrants.keep }}
  annotations:
    "helm.sh/resource-policy": keep
  {{- end }}
spec:
  bucket: {{ .Values.nats.kv_bucket_meeting_registrants.name }}
  history: {{ .Values.nats.kv_bucket_meeting_registrants.history }}
  storage: {{ .Values.nats.kv_bucket_meeting_registrants.storage }}
  maxValueSize: {{ .Values.nats.kv_bucket_meeting_registrants.maxValueSize }}
  maxBytes: {{ .Values.nats.kv_bucket_meeting_registrants.maxBytes }}
  compression: {{ .Values.nats.kv_bucket_meeting_registrants.compression }}
{{- end }}
---
{{- if .Values.nats.kv_bucket_meeting_rsvp.creation }}
apiVersion: jetstream.nats.io/v1beta2
kind: KeyValue
metadata:
  name: {{ .Values.nats.kv_bucket_meeting_rsvp.name }}
  namespace: lfx
  {{- if .Values.nats.kv_bucket_meeting_rsvp.keep }}
  annotations:
    "helm.sh/resource-policy": keep
  {{- end }}
spec:
  bucket: {{ .Values.nats.kv_bucket_meeting_rsvp.name }}
  history: {{ .Values.nats.kv_bucket_meeting_rsvp.history }}
  storage: {{ .Values.nats.kv_bucket_meeting_rsvp.storage }}
  maxValueSize: {{ .Values.nats.kv_bucket_meeting_rsvp.maxValueSize }}
  maxBytes: {{ .Values.nats.kv_bucket_meeting_rsvp.maxBytes }}
  compression: {{ .Values.nats.kv_bucket_meeting_rsvp.compression }}
{{- end }}
---
{{- if .Values.nats.kv_bucket_past_meetings.creation }}
apiVersion: jetstream.nats.io/v1beta2
kind: KeyValue
metadata:
  name: {{ .Values.nats.kv_bucket_past_meetings.name }}
  namespace: lfx
  {{- if .Values.nats.kv_bucket_past_meetings.keep }}
  annotations:
    "helm.sh/resource-policy": keep
  {{- end }}
spec:
  bucket: {{ .Values.nats.kv_bucket_past_meetings.name }}
  history: {{ .Values.nats.kv_bucket_past_meetings.history }}
  storage: {{ .Values.nats.kv_bucket_past_meetings.storage }}
  maxValueSize: {{ .Values.nats.kv_bucket_past_meetings.maxValueSize }}
  maxBytes: {{ .Values.nats.kv_bucket_past_meetings.maxBytes }}
  compression: {{ .Values.nats.kv_bucket_past_meetings.compression }}
{{- end }}
---
{{- if .Values.nats.kv_bucket_past_meeting_participants.creation }}
apiVersion: jetstream.nats.io/v1beta2
kind: KeyValue
metadata:
  name: {{ .Values.nats.kv_bucket_past_meeting_participants.name }}
  namespace: lfx
  {{- if .Values.nats.kv_bucket_past_meeting_participants.keep }}
  annotations:
    "helm.sh/resource-policy": keep
  {{- end }}
spec:
  bucket: {{ .Values.nats.kv_bucket_past_meeting_participants.name }}
  history: {{ .Values.nats.kv_bucket_past_meeting_participants.history }}
  storage: {{ .Values.nats.kv_bucket_past_meeting_participants.storage }}
  maxValueSize: {{ .Values.nats.kv_bucket_past_meeting_participants.maxValueSize }}
  maxBytes: {{ .Values.nats.kv_bucket_past_meeting_participants.maxBytes }}
  compression: {{ .Values.nats.kv_bucket_past_meeting_participants.compression }}
{{- end }}
---
{{- if .Values.nats.kv_bucket_past_meeting_recordings.creation }}
apiVersion: jetstream.nats.io/v1beta2
kind: KeyValue
metadata:
  name: {{ .Values.nats.kv_bucket_past_meeting_recordings.name }}
  namespace: lfx
  {{- if .Values.nats.kv_bucket_past_meeting_recordings.keep }}
  annotations:
    "helm.sh/resource-policy": keep
  {{- end }}
spec:
  bucket: {{ .Values.nats.kv_bucket_past_meeting_recordings.name }}
  history: {{ .Values.nats.kv_bucket_past_meeting_recordings.history }}
  storage: {{ .Values.nats.kv_bucket_past_meeting_recordings.storage }}
  maxValueSize: {{ .Values.nats.kv_bucket_past_meeting_recordings.maxValueSize }}
  maxBytes: {{ .Values.nats.kv_bucket_past_meeting_recordings.maxBytes }}
  compression: {{ .Values.nats.kv_bucket_past_meeting_recordings.compression }}
{{- end }}
---
{{- if .Values.nats.kv_bucket_past_meeting_transcripts.creation }}
apiVersion: jetstream.nats.io/v1beta2
kind: KeyValue
metadata:
  name: {{ .Values.nats.kv_bucket_past_meeting_transcripts.name }}
  namespace: lfx
  {{- if .Values.nats.kv_bucket_past_meeting_transcripts.keep }}
  annotations:
    "helm.sh/resource-policy": keep
  {{- end }}
spec:
  bucket: {{ .Values.nats.kv_bucket_past_meeting_transcripts.name }}
  history: {{ .Values.nats.kv_bucket_past_meeting_transcripts.history }}
  storage: {{ .Values.nats.kv_bucket_past_meeting_transcripts.storage }}
  maxValueSize: {{ .Values.nats.kv_bucket_past_meeting_transcripts.maxValueSize }}
  maxBytes: {{ .Values.nats.kv_bucket_past_meeting_transcripts.maxBytes }}
  compression: {{ .Values.nats.kv_bucket_past_meeting_transcripts.compression }}
{{- end }}
---
{{- if .Values.nats.kv_bucket_past_meeting_summaries.creation }}
apiVersion: jetstream.nats.io/v1beta2
kind: KeyValue
metadata:
  name: {{ .Values.nats.kv_bucket_past_meeting_summaries.name }}
  namespace: lfx
  {{- if .Values.nats.kv_bucket_past_meeting_summaries.keep }}
  annotations:
    "helm.sh/resource-policy": keep
  {{- end }}
spec:
  bucket: {{ .Values.nats.kv_bucket_past_meeting_summaries.name }}
  history: {{ .Values.nats.kv_bucket_past_meeting_summaries.history }}
  storage: {{ .Values.nats.kv_bucket_past_meeting_summaries.storage }}
  maxValueSize: {{ .Values.nats.kv_bucket_past_meeting_summaries.maxValueSize }}
  maxBytes: {{ .Values.nats.kv_bucket_past_meeting_summaries.maxBytes }}
  compression: {{ .Values.nats.kv_bucket_past_meeting_summaries.compression }}
{{- end }}

---
{{- if .Values.nats.kv_bucket_meeting_attachments_metadata.creation }}
apiVersion: jetstream.nats.io/v1beta2
kind: KeyValue
metadata:
  name: {{ .Values.nats.kv_bucket_meeting_attachments_metadata.name }}
  namespace: lfx
  {{- if .Values.nats.kv_bucket_meeting_attachments_metadata.keep }}
  annotations:
    "helm.sh/resource-policy": keep
  {{- end }}
spec:
  bucket: {{ .Values.nats.kv_bucket_meeting_attachments_metadata.name }}
  history: {{ .Values.nats.kv_bucket_meeting_attachments_metadata.history }}
  storage: {{ .Values.nats.kv_bucket_meeting_attachments_metadata.storage }}
  maxValueSize: {{ .Values.nats.kv_bucket_meeting_attachments_metadata.maxValueSize }}
  maxBytes: {{ .Values.nats.kv_bucket_meeting_attachments_metadata.maxBytes }}
  compression: {{ .Values.nats.kv_bucket_meeting_attachments_metadata.compression }}
{{- end }}
